version: '3'

services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  default:
    name: apache-kafka_default
    external: true
